/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayModeRouteImport } from './routes/play.$mode'
import { Route as ApiGenerateLevelImagesRouteImport } from './routes/api/generate-level-images'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as PlayModeLevelIdRouteImport } from './routes/play.$mode.$levelId'
import { Route as AuthenticatedAdminLevelsIdRouteImport } from './routes/_authenticated/admin/levels.$id'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayModeRoute = PlayModeRouteImport.update({
  id: '/play/$mode',
  path: '/play/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateLevelImagesRoute = ApiGenerateLevelImagesRouteImport.update({
  id: '/api/generate-level-images',
  path: '/api/generate-level-images',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlayModeLevelIdRoute = PlayModeLevelIdRouteImport.update({
  id: '/$levelId',
  path: '/$levelId',
  getParentRoute: () => PlayModeRoute,
} as any)
const AuthenticatedAdminLevelsIdRoute =
  AuthenticatedAdminLevelsIdRouteImport.update({
    id: '/admin/levels/$id',
    path: '/admin/levels/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/generate-level-images': typeof ApiGenerateLevelImagesRoute
  '/play/$mode': typeof PlayModeRouteWithChildren
  '/play/$mode/$levelId': typeof PlayModeLevelIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/levels/$id': typeof AuthenticatedAdminLevelsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/generate-level-images': typeof ApiGenerateLevelImagesRoute
  '/play/$mode': typeof PlayModeRouteWithChildren
  '/play/$mode/$levelId': typeof PlayModeLevelIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/levels/$id': typeof AuthenticatedAdminLevelsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/generate-level-images': typeof ApiGenerateLevelImagesRoute
  '/play/$mode': typeof PlayModeRouteWithChildren
  '/play/$mode/$levelId': typeof PlayModeLevelIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/levels/$id': typeof AuthenticatedAdminLevelsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/sitemap.xml'
    | '/story'
    | '/profile'
    | '/api/generate-level-images'
    | '/play/$mode'
    | '/play/$mode/$levelId'
    | '/admin/'
    | '/admin/levels/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/sitemap.xml'
    | '/story'
    | '/profile'
    | '/api/generate-level-images'
    | '/play/$mode'
    | '/play/$mode/$levelId'
    | '/admin'
    | '/admin/levels/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/leaderboard'
    | '/sitemap.xml'
    | '/story'
    | '/_authenticated/profile'
    | '/api/generate-level-images'
    | '/play/$mode'
    | '/play/$mode/$levelId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/levels/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  ApiGenerateLevelImagesRoute: typeof ApiGenerateLevelImagesRoute
  PlayModeRoute: typeof PlayModeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$mode': {
      id: '/play/$mode'
      path: '/play/$mode'
      fullPath: '/play/$mode'
      preLoaderRoute: typeof PlayModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-level-images': {
      id: '/api/generate-level-images'
      path: '/api/generate-level-images'
      fullPath: '/api/generate-level-images'
      preLoaderRoute: typeof ApiGenerateLevelImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/play/$mode/$levelId': {
      id: '/play/$mode/$levelId'
      path: '/$levelId'
      fullPath: '/play/$mode/$levelId'
      preLoaderRoute: typeof PlayModeLevelIdRouteImport
      parentRoute: typeof PlayModeRoute
    }
    '/_authenticated/admin/levels/$id': {
      id: '/_authenticated/admin/levels/$id'
      path: '/admin/levels/$id'
      fullPath: '/admin/levels/$id'
      preLoaderRoute: typeof AuthenticatedAdminLevelsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminLevelsIdRoute: typeof AuthenticatedAdminLevelsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminLevelsIdRoute: AuthenticatedAdminLevelsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlayModeRouteChildren {
  PlayModeLevelIdRoute: typeof PlayModeLevelIdRoute
}

const PlayModeRouteChildren: PlayModeRouteChildren = {
  PlayModeLevelIdRoute: PlayModeLevelIdRoute,
}

const PlayModeRouteWithChildren = PlayModeRoute._addFileChildren(
  PlayModeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  ApiGenerateLevelImagesRoute: ApiGenerateLevelImagesRoute,
  PlayModeRoute: PlayModeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
